# Generated by Django 5.2.5 on 2025-12-20 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transactions',
            options={'verbose_name': 'Transaction', 'verbose_name_plural': 'Transactions'},
        ),
        migrations.AlterModelOptions(
            name='virtualaccount',
            options={'verbose_name': 'Compte', 'verbose_name_plural': 'Comptes'},
        ),
    ]
