# Generated by Django 5.2.9 on 2025-12-20 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauths', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('f', 'F'), ('m', 'M')], max_length=10),
        ),
    ]
