# Generated by Django 5.2.5 on 2025-12-20 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauths', '0002_alter_user_gender'),
    ]

    operations = [
        migrations.CreateModel(
            name='OPT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField()),
                ('updated_at', models.DateField()),
                ('deleted_at', models.DateField()),
                ('code', models.CharField(max_length=10)),
                ('is_expire', models.BooleanField()),
                ('expire_at', models.DateTimeField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='user',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('SUSPENDED', 'Suspended'), ('PENDING', 'Pending')], default='active', max_length=20),
        ),
    ]
