# Generated by Django 5.2.5 on 2025-12-20 14:20

import shortuuid.django_fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userauths', '0003_opt_alter_user_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='opt',
            options={'verbose_name': 'Opt', 'verbose_name_plural': 'Opt'},
        ),
        migrations.AddField(
            model_name='opt',
            name='id_opt',
            field=shortuuid.django_fields.ShortUUIDField(alphabet='124', length=2, max_length=5, prefix='', unique=True),
        ),
    ]
