# Generated by Django 5.2.5 on 2025-12-21 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauths', '0004_alter_opt_options_opt_id_opt'),
    ]

    operations = [
        migrations.CreateModel(
            name='OTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('deleted_at', models.DateField(blank=True, null=True)),
                ('code', models.CharField(max_length=10)),
                ('is_expire', models.BooleanField()),
                ('expire_at', models.DateTimeField()),
            ],
            options={
                'verbose_name': 'Otp',
                'verbose_name_plural': 'Otpt',
            },
        ),
        migrations.DeleteModel(
            name='OPT',
        ),
    ]
