# Generated by Django 5.2.5 on 2025-12-22 00:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userauths', '0005_otp_delete_opt'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='password_hash',
        ),
    ]
