# Generated by Django 5.2.5 on 2025-12-22 23:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_platform_options_accountowner_platform_and_more'),
        ('userauths', '0006_remove_user_password_hash'),
    ]

    operations = [
        migrations.AddField(
            model_name='otp',
            name='account_owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.accountowner'),
            preserve_default=False,
        ),
    ]
